name: Automatic releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:

  build:
    name: Build & publish
    runs-on: ubuntu-latest    
    steps:
    - name: Checkouting code...
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Preparing nuget source
      run: dotnet nuget add source --username SkyCD --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SkyCD/index.json"        

    - name: Restoring packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
      
    - name: Releasing if there is something new...
      uses: impresscms-dev/simple-autorelease-action@v0.1
      with:
        release_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
      
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=$(git describe --tags --dirty | sed 's/[[:alpha:]|(|[:space:]]//g')            

    - name: Publish to GitHub packages 
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
